#include "core/pdexternals.h"

extern "C" {
// cyclone (porres/pd-cyclone, CYCLONE_SINGLE_LIBRARY mode): registers
// the 12 non-alphanumeric cyclone objects and then setup_single_lib()
// (generated single_lib.c) registers every audio/control object.
void cyclone_setup(void);
// else (porres/pd-else): generated by cmake/pdexternals.cmake; calls
// every *_setup of the compiled else objects (the else.c bootstrap is
// excluded on purpose - it pulls in lua + TCL GUI plugins).
void register_else_objects(void);
}

namespace godot_libpd {

void register_pdexternals() {
	cyclone_setup();
	register_else_objects();
}

} // namespace godot_libpd
