# Vendored pd externals: porres/pd-cyclone + porres/pd-else, compiled as
# static libraries against the vendored (stripped) pd headers and linked
# into the extension + host tests. Registration is one call per process
# (core/pdexternals.cpp -> register_pdexternals), run from
# LibpdWorker::init_pd_globals_once() after libpd_init(); class
# registration then reaches every instance (class_doaddmethod iterates
# all pd_ninstances; pdinstance_new re-registers for future ones).
#
# Scope (spec: pd-externals): control + sound generation. Excluded from
# the ELSE build: the else.c bootstrap (lua + TCL plugin loading),
# lua-dependent objects (pdlink~/pdlink), aubio-dependent (beat~),
# ffmpeg-dependent objects
# (streamin~/streamout~/play.file~), soundfile-backend objects
# (sfinfo/sfload), and the heavy vendored sub-trees (sfz~/sfizz,
# circuit~, ffmpeg, opus, vorbis, aubio, link/). GUI-only widgets that
# cannot render in the embedded build (popmenu, numbox~) are blacklisted;
# message-driven canvas widgets (knob, button, pad, bicoeff, messcoll)
# are kept - their GUI messaging is a no-op headless and their object
# logic works (see exclusion list below).

set(PDEXTERNALS_PD_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libpd/pure-data/src")
set(PDEXTERNALS_CYCLONE_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/cyclone")
set(PDEXTERNALS_ELSE_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/else")
set(PDEXTERNALS_GEN_DIR "${CMAKE_CURRENT_BINARY_DIR}/pdexternals-gen")
file(MAKE_DIRECTORY "${PDEXTERNALS_GEN_DIR}")

# ---------------------------------------------------------------------------
# cyclone: single-library mode (the repo's single_lib.c.in template is
# filled with every object's setup function; cyclone_setup() then calls
# setup_single_lib() when CYCLONE_SINGLE_LIBRARY is defined).
# ---------------------------------------------------------------------------
file(GLOB PDEXTERNALS_CYCLONE_OBJECT_SOURCES
    "${PDEXTERNALS_CYCLONE_ROOT}/cyclone_objects/binaries/audio/*.c"
    "${PDEXTERNALS_CYCLONE_ROOT}/cyclone_objects/binaries/control/*.c")
# Filter: keep only real object sources (defined via CYCLONE_OBJ_API). This
# drops Tcl-only dialog scripts such as audio/scope_dialog.c, which are
# sys_gui() text dumps, not compilable C objects.
set(_cyclone_kept "")
foreach(_src IN LISTS PDEXTERNALS_CYCLONE_OBJECT_SOURCES)
    file(READ "${_src}" _content)
    if(_content MATCHES "CYCLONE_OBJ_API")
        list(APPEND _cyclone_kept "${_src}")
    else()
        message(STATUS "pdexternals: skipping non-object cyclone source ${_src}")
    endif()
endforeach()
set(PDEXTERNALS_CYCLONE_OBJECT_SOURCES ${_cyclone_kept})

# comment.c calls the cyclone_u8_* names (cyclone's renamed copy of the
# pd u8_* API). Since s_cycloneutf8.c is out (collides with pd core
# s_utf8.c), compile comment.c with the names mapped back to the core.
set(_comment_wrapper "// Generated by pdexternals.cmake - do not edit.\n")
string(APPEND _comment_wrapper "#define cyclone_u8_wc_nbytes u8_wc_nbytes\n")
string(APPEND _comment_wrapper "#define cyclone_u8_inc u8_inc\n")
string(APPEND _comment_wrapper "#define cyclone_u8_dec u8_dec\n\n")
string(APPEND _comment_wrapper
    "#include \"${PDEXTERNALS_CYCLONE_ROOT}/cyclone_objects/binaries/control/comment.c\"\n")
file(WRITE "${PDEXTERNALS_GEN_DIR}/comment_nodup.c" "${_comment_wrapper}")
list(REMOVE_ITEM PDEXTERNALS_CYCLONE_OBJECT_SOURCES
    "${PDEXTERNALS_CYCLONE_ROOT}/cyclone_objects/binaries/control/comment.c")
list(APPEND PDEXTERNALS_CYCLONE_OBJECT_SOURCES
    "${PDEXTERNALS_GEN_DIR}/comment_nodup.c")
set(PDEXTERNALS_CYCLONE_SOURCES ${PDEXTERNALS_CYCLONE_OBJECT_SOURCES}
    "${PDEXTERNALS_CYCLONE_ROOT}/cyclone_objects/binaries/cyclone_lib.c"
    # cyclone's shared support lib (mirrors upstream cyclone_shared:
    # file/grow/magicbit/random, gui/mifi/rand/utf8/tree, cybuf ring buffer)
    "${PDEXTERNALS_CYCLONE_ROOT}/shared/common/file.c"
    "${PDEXTERNALS_CYCLONE_ROOT}/shared/common/grow.c"
    "${PDEXTERNALS_CYCLONE_ROOT}/shared/common/magicbit.c"
    "${PDEXTERNALS_CYCLONE_ROOT}/shared/common/random.c"
    "${PDEXTERNALS_CYCLONE_ROOT}/shared/control/gui.c"
    "${PDEXTERNALS_CYCLONE_ROOT}/shared/control/mifi.c"
    "${PDEXTERNALS_CYCLONE_ROOT}/shared/control/rand.c"
    # (s_cycloneutf8.c excluded: its u8_* copies collide with the pd
    # core's s_utf8.c; comment.c is wrapped to call the core copy)
    "${PDEXTERNALS_CYCLONE_ROOT}/shared/control/tree.c"
    "${PDEXTERNALS_CYCLONE_ROOT}/shared/signal/cybuf.c")

set(_cyclone_setup_funcs "")
set(_cyclone_decls "")
set(_cyclone_calls "")
foreach(_src IN LISTS PDEXTERNALS_CYCLONE_OBJECT_SOURCES)
    file(READ "${_src}" _content)
    string(REGEX MATCHALL
        "CYCLONE_OBJ_API[ \t]+void[ \t]+[A-Za-z0-9_]+_setup[ \t]*\\("
        _matches "${_content}")
    foreach(_m IN LISTS _matches)
        string(REGEX REPLACE
            "CYCLONE_OBJ_API[ \t]+void[ \t]+([A-Za-z0-9_]+_setup)[ \t]*\\("
            "\\1" _fn "${_m}")
        if(NOT _fn IN_LIST _cyclone_setup_funcs)
            list(APPEND _cyclone_setup_funcs "${_fn}")
            string(APPEND _cyclone_decls "void ${_fn}(void);\n")
            string(APPEND _cyclone_calls "    ${_fn}();\n")
        endif()
    endforeach()
endforeach()
list(LENGTH _cyclone_setup_funcs _cyclone_count)
message(STATUS "pdexternals: cyclone ${_cyclone_count} setup functions found")
set(SETUP_DECLS "${_cyclone_decls}")
set(SETUP_CALLS "${_cyclone_calls}")
configure_file(
    "${PDEXTERNALS_CYCLONE_ROOT}/cyclone_objects/binaries/single_lib.c.in"
    "${PDEXTERNALS_GEN_DIR}/cyclone_single_lib.c" @ONLY)

add_library(cyclone STATIC
    ${PDEXTERNALS_CYCLONE_SOURCES}
    "${PDEXTERNALS_GEN_DIR}/cyclone_single_lib.c")
target_include_directories(cyclone PUBLIC
    "${PDEXTERNALS_PD_SRC}"
    "${PDEXTERNALS_CYCLONE_ROOT}/shared")
# Multi-instance libpd build: externals must see the same per-instance
# macro layout as the pd core (s_* are pd_this->pd_s_* members, not
# globals - compiling without these makes externals reference global
# s_bang/s_/... that do not exist in libpd-multi.a).
target_compile_definitions(cyclone PRIVATE
    PDINSTANCE=1 PDTHREADS=1 PD_INTERNAL=1
    CYCLONE_SINGLE_LIBRARY=1)
target_compile_options(cyclone PRIVATE
    -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast)

# ---------------------------------------------------------------------------
# else: top-level Audio/ + Control/ + Shared/ sources minus the excluded
# dependency-heavy files; generated else_register.c calls every
# *_setup()/setup_*(void) found in the built files.
# ---------------------------------------------------------------------------
file(GLOB PDEXTERNALS_ELSE_SOURCES
    "${PDEXTERNALS_ELSE_ROOT}/Source/Audio/*.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Control/*.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Shared/*.c"
    # fftease (phase-voice resynthesis, used by pvretune~ - self-contained)
    "${PDEXTERNALS_ELSE_ROOT}/Source/Shared/fftease/*.c")
set(PDEXTERNALS_ELSE_EXCLUDE
    # bootstrap object: calls lua_setup() + loads TCL GUI plugins
    "${PDEXTERNALS_ELSE_ROOT}/Source/Control/else.c"
    # GUI-only widgets whose entire purpose is a dialog/canvas widget that
    # can never render in the embedded build (blacklisted from the build).
    # Note: knob is deliberately KEPT - it is also a message-driven control
    # object (set/inc/dec/range/jump/param); its dialog + canvas drawing are
    # harmless no-ops headless (pdgui_vmess/pdgui_stub_vnew).
    "${PDEXTERNALS_ELSE_ROOT}/Source/Control/popmenu.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Audio/numbox~.c"
    # link-protocol objects (pull in the C++/UDP Source/Shared/link lib)
    "${PDEXTERNALS_ELSE_ROOT}/Source/Audio/pdlink~.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Control/pdlink.c"
    # duplicate objects: same class name AND same C symbols as the
    # cyclone equivalents (tanh/trunc/atan2~/car2pol~+cartopol alias/
    # pol2car~/scope~) - cyclone copies are kept
    "${PDEXTERNALS_ELSE_ROOT}/Source/Control/tanh.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Control/trunc.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Control/car2pol.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Control/pol2car.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Audio/tanh~.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Audio/trunc~.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Audio/atan2~.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Audio/car2pol~.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Audio/pol2car~.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Audio/scope~.c"
    # coll_checkint symbol collides with cyclone's coll (GUI widget;
    # cyclone [coll] covers the functionality)
    "${PDEXTERNALS_ELSE_ROOT}/Source/Control/messcoll.c"
    # support code already provided by the pd core / cyclone (raw files;
    # the renamed wrappers below replace where the API overlaps)
    "${PDEXTERNALS_ELSE_ROOT}/Source/Shared/mifi.c"       # mifiread/write: cyclone
    "${PDEXTERNALS_ELSE_ROOT}/Source/Shared/elsefile.c"   # file API: cyclone
    "${PDEXTERNALS_ELSE_ROOT}/Source/Shared/s_elseutf8.c" # u8_*: pd s_utf8.c
    # aubio-dependent
    "${PDEXTERNALS_ELSE_ROOT}/Source/Audio/beat~.c"
    # ffmpeg-dependent
    "${PDEXTERNALS_ELSE_ROOT}/Source/Audio/streamin~.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Audio/streamout~.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Audio/play.file~.c"
    # soundfile-backend objects (ffmpeg/vorbis decode)
    "${PDEXTERNALS_ELSE_ROOT}/Source/Control/sfinfo.c"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Control/sfload.c")
foreach(_excl IN LISTS PDEXTERNALS_ELSE_EXCLUDE)
    list(REMOVE_ITEM PDEXTERNALS_ELSE_SOURCES "${_excl}")
endforeach()

# elsefile.c defines the same krzYszcz file-API globals (osdir_*,
# ospath_*, fileread_open, filewrite_open, panel_*, embed_save) as
# cyclone's shared/common/file.c - static-archive symbol collision.
# Compile a wrapper that renames else's copy (the elsefile_*-prefixed
# API stays; else objects calling the raw names bind to cyclone's
# identical-impl copy).
set(_elsefile_dup_syms
    ospath_length ospath_absolute
    osdir_open osdir_setmode osdir_close osdir_rewind
    osdir_next osdir_isfile osdir_isdir
    fileread_open filewrite_open
    panel_getopendir panel_getsavedir panel_setopendir panel_setsavedir
    embed_save)
set(_elsefile_wrapper "// Generated by pdexternals.cmake - do not edit.\n")
foreach(_sym IN LISTS _elsefile_dup_syms)
    string(APPEND _elsefile_wrapper "#define ${_sym} else_${_sym}\n")
endforeach()
string(APPEND _elsefile_wrapper "\n")
string(APPEND _elsefile_wrapper
    "#include \"${PDEXTERNALS_ELSE_ROOT}/Source/Shared/elsefile.c\"\n")
file(WRITE "${PDEXTERNALS_GEN_DIR}/elsefile_nodup.c" "${_elsefile_wrapper}")
list(APPEND PDEXTERNALS_ELSE_SOURCES "${PDEXTERNALS_GEN_DIR}/elsefile_nodup.c")

# Same trick for s_elseutf8.c: its plain u8_* set collides with the pd
# core's s_utf8.c; keep the else-prefixed else_u8_* (used by else
# objects) and rename the plain u8_* to else_u8_*.
set(_elseutf8_dup_syms
    u8_seqlen u8_utf8toucs2 u8_ucs2toutf8 u8_wc_toutf8
    u8_wc_toutf8_nul u8_offset u8_charnum u8_strlen
    u8_nativetoutf8 u8_nextchar)
set(_elseutf8_wrapper "// Generated by pdexternals.cmake - do not edit.\n")
foreach(_sym IN LISTS _elseutf8_dup_syms)
    string(APPEND _elseutf8_wrapper "#define ${_sym} else_${_sym}\n")
endforeach()
string(APPEND _elseutf8_wrapper "\n")
string(APPEND _elseutf8_wrapper
    "#include \"${PDEXTERNALS_ELSE_ROOT}/Source/Shared/s_elseutf8.c\"\n")
file(WRITE "${PDEXTERNALS_GEN_DIR}/s_elseutf8_nodup.c" "${_elseutf8_wrapper}")
list(APPEND PDEXTERNALS_ELSE_SOURCES "${PDEXTERNALS_GEN_DIR}/s_elseutf8_nodup.c")

set(_else_names "")
set(_else_decls "")
set(_else_calls "")
foreach(_src IN LISTS PDEXTERNALS_ELSE_SOURCES)
    file(READ "${_src}" _content)
    # two naming styles: plain "xxx_setup" and hex-encoded
    # "setup_xxx" (else encodes non-alphanumeric object names).
    string(REGEX MATCHALL
        "void[ \t]+[A-Za-z0-9_]+_setup[ \t]*\\([ \t]*void[ \t]*\\)"
        _m1 "${_content}")
    string(REGEX MATCHALL
        "void[ \t]+setup_[A-Za-z0-9_]+[ \t]*\\(\\)"
        _m2 "${_content}")
    set(_matches ${_m1} ${_m2})
    foreach(_m IN LISTS _matches)
        # NOTE: string(REGEX REPLACE) writes the WHOLE input string into the
        # output variable when the pattern does not match - so each pattern
        # needs its own output variable, not one reused variable.
        string(REGEX REPLACE
            "void[ \t]+([A-Za-z0-9_]+)[ \t]*\\([ \t]*void[ \t]*\\)"
            "\\1" _name1 "${_m}")
        string(REGEX REPLACE
            "void[ \t]+(setup_[A-Za-z0-9_]+)[ \t]*\\(\\)"
            "\\1" _name2 "${_m}")
        if(NOT _name1 STREQUAL "${_m}")
            set(_name "${_name1}")
        else()
            set(_name "${_name2}")
        endif()
        if(NOT _name IN_LIST _else_names)
            list(APPEND _else_names "${_name}")
            string(APPEND _else_decls "void ${_name}(void);\n")
            string(APPEND _else_calls "    ${_name}();\n")
        endif()
    endforeach()
endforeach()
list(LENGTH _else_names _else_count)
message(STATUS "pdexternals: else ${_else_count} setup functions found")

set(_else_register "// Generated by pdexternals.cmake - do not edit.\n\n")
foreach(_n IN LISTS _else_names)
    string(APPEND _else_register "void ${_n}(void);\n")
endforeach()
string(APPEND _else_register "void register_else_objects(void)\n{\n")
string(APPEND _else_register "${_else_calls}")
string(APPEND _else_register "}\n")
file(WRITE "${PDEXTERNALS_GEN_DIR}/else_register.c" "${_else_register}")

add_library(pdelse STATIC
    ${PDEXTERNALS_ELSE_SOURCES}
    "${PDEXTERNALS_GEN_DIR}/else_register.c")
target_include_directories(pdelse PUBLIC
    "${PDEXTERNALS_PD_SRC}"
    "${PDEXTERNALS_ELSE_ROOT}/Source/Shared")
target_compile_definitions(pdelse PRIVATE PDINSTANCE=1 PDTHREADS=1 PD_INTERNAL=1)
target_compile_options(pdelse PRIVATE
    -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast)

# ---------------------------------------------------------------------------
# In-house external: externals/tjcount (tj externals series). The same
# source builds as a classic Pd/Plugdata external (its own makefile) and
# here as a static lib for the embedded build; registration via
# core/pdexternals.cpp -> tjcount_setup().
# ---------------------------------------------------------------------------
set(PDEXTERNALS_TJ_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../externals/tjcount")
add_library(tjcount STATIC
    "${PDEXTERNALS_TJ_ROOT}/tjcount.c")
target_include_directories(tjcount PUBLIC "${PDEXTERNALS_PD_SRC}")
target_compile_definitions(tjcount PRIVATE
    PDINSTANCE=1 PDTHREADS=1 PD_INTERNAL=1)
target_compile_options(tjcount PRIVATE
    -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast)

# In-house external: externals/tjlistfind (tj externals series) - same
# dual build as tjcount.
set(PDEXTERNALS_TJLISTFIND_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../externals/tjlistfind")
add_library(tjlistfind STATIC
    "${PDEXTERNALS_TJLISTFIND_ROOT}/tjlistfind.c")
target_include_directories(tjlistfind PUBLIC "${PDEXTERNALS_PD_SRC}")
target_compile_definitions(tjlistfind PRIVATE
    PDINSTANCE=1 PDTHREADS=1 PD_INTERNAL=1)
target_compile_options(tjlistfind PRIVATE
    -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast)
